"use client";

import { useMemo } from "react";
import { buildSelectedWorkspaceViewState } from "../domain/workspaceView";

export function useAdminWorkspaceView({
  selected,
  identity,
  story,
  contentPack,
  order,
  qrDataUrl,
  dolls,
  contentManagementByDoll,
  selectedContentManagement,
  selectedGeneratedV1Content,
  activeDepartment,
  activeStageView,
  selectedWorkspaceMode,
  operationsFilter,
  operationsSort,
  selectedSlug,
  publicPath,
  publicUrl,
  savedSlug,
  legacyLockedSlug,
  error,
  notice,
}) {
  return useMemo(
    () =>
      buildSelectedWorkspaceViewState({
        selected,
        identity,
        story,
        contentPack,
        order,
        qrDataUrl,
        dolls,
        contentManagementByDoll,
        selectedContentManagement,
        selectedGeneratedV1Content,
        activeDepartment,
        activeStageView,
        selectedWorkspaceMode,
        operationsFilter,
        operationsSort,
        selectedSlug,
        publicPath,
        publicUrl,
        savedSlug,
        legacyLockedSlug,
        error,
        notice,
      }),
    [
      activeDepartment,
      activeStageView,
      contentManagementByDoll,
      contentPack,
      dolls,
      error,
      identity,
      legacyLockedSlug,
      notice,
      operationsFilter,
      operationsSort,
      order,
      publicPath,
      publicUrl,
      qrDataUrl,
      savedSlug,
      selected,
      selectedContentManagement,
      selectedGeneratedV1Content,
      selectedSlug,
      selectedWorkspaceMode,
      story,
    ]
  );
}
