export function buildAdminProductionSectionState({
  selected,
  isProductionEditable,
  dollIdentityCollection,
  dollIdentityArtistDisplay,
  dollIdentityArtistIsEmpty,
  currentWorkflowStageLabel,
  currentWorkflowStageStatus,
  dollIdentityWorkflowState,
  identity,
  setIdentity,
  hasImage,
  uploadImage,
  saveIdentity,
} = {}) {
  return {
    isProductionEditable: Boolean(isProductionEditable),
    dollIdentity: {
      name: selected?.name || "",
      internalId: selected?.internal_id || "",
      collection: dollIdentityCollection || "",
      artistDisplay: dollIdentityArtistDisplay || "",
      artistIsEmpty: Boolean(dollIdentityArtistIsEmpty),
      workflowStageLabel: currentWorkflowStageLabel || "",
      workflowStageStatus: currentWorkflowStageStatus || "",
      workflowState: dollIdentityWorkflowState || "",
    },
    identity,
    setIdentity,
    hasImage: Boolean(hasImage),
    uploadImage,
    saveIdentity,
  };
}

export function buildAdminSelectionSectionState({
  selected,
  selectedIsArchived,
  selectedReadinessOverall,
  currentSelectedWorkspaceMode,
  setSelectedWorkspaceMode,
  selectedWorkspaceHeading,
  selectedWorkspaceSummary,
  currentDepartment,
  setActiveDepartment,
  currentStageView,
  setActiveStageView,
} = {}) {
  return {
    selected: selected ?? null,
    selectedId: selected?.id ?? null,
    selectedIsArchived: Boolean(selectedIsArchived),
    selectedReadinessOverall: Boolean(selectedReadinessOverall),
    currentSelectedWorkspaceMode: currentSelectedWorkspaceMode || "",
    setSelectedWorkspaceMode,
    selectedWorkspaceHeading: selectedWorkspaceHeading || "",
    selectedWorkspaceSummary: selectedWorkspaceSummary || "",
    currentDepartment: currentDepartment || "",
    setActiveDepartment,
    currentStageView: currentStageView || "",
    setActiveStageView,
  };
}

export function buildAdminStageActionSectionState({
  warning,
  clearWarning,
  confirmWarning,
} = {}) {
  return {
    warning: warning ?? null,
    clearWarning,
    confirmWarning,
  };
}

export function buildAdminAuthenticatedShellState({
  adminProtectionEnabled,
  handleLogout,
  adminVersionLabel,
  selectedSlug,
  publicUrl,
  publicPath,
  operationsFilter,
  setOperationsFilter,
  operationsSort,
  setOperationsSort,
  contentSectionState,
  browserActionsState = {},
  catalogState = {},
  detailState = {},
  identityEditorState = {},
  selectionState = {},
  workspaceViewState = {},
  commerceEditorState = {},
  managedContentStoreState = {},
  managedContentState = {},
  pipelineActionsState = {},
  qrWorkflowState = {},
  dangerZoneState = {},
  clearStageActionWarning,
} = {}) {
  const selected = catalogState.selected ?? null;

  return {
    auth: {
      adminProtectionEnabled: Boolean(adminProtectionEnabled),
      handleLogout,
    },
    catalog: {
      dolls: Array.isArray(catalogState.dolls) ? catalogState.dolls : [],
      refreshCatalog: catalogState.refreshCatalog,
      selectDoll: selectionState.selectDoll,
      adminVersionLabel: adminVersionLabel || "",
    },
    character: {
      isCharacterEditable: Boolean(workspaceViewState.isCharacterEditable),
      identity: detailState.identity,
      setIdentity: detailState.setIdentity,
      themes: Array.isArray(catalogState.themes) ? catalogState.themes : [],
      saveIdentity: identityEditorState.saveIdentity,
    },
    commerce: {
      commerceStatus: detailState.commerceStatus || "draft",
      setCommerceStatus: detailState.setCommerceStatus,
      effectiveCommerceStatus: workspaceViewState.effectiveCommerceStatus || "draft",
      effectiveAccessStatus: workspaceViewState.effectiveAccessStatus || "",
      isGatewayEditable: Boolean(workspaceViewState.isGatewayEditable),
      commerceSaving: Boolean(commerceEditorState.commerceSaving),
      saveCommerceStatus: commerceEditorState.saveCommerceStatus,
      order: detailState.order,
      setOrder: detailState.setOrder,
      saveOrder: commerceEditorState.saveOrder,
    },
    content: contentSectionState,
    danger: {
      dangerAction: dangerZoneState.dangerAction || "",
      dangerLoading: Boolean(dangerZoneState.dangerLoading),
      archiveWarningMessage: workspaceViewState.archiveWarningMessage || "",
      deleteWarningMessage: workspaceViewState.deleteWarningMessage || "",
      dangerNeedsTypedDelete: Boolean(workspaceViewState.dangerNeedsTypedDelete),
      dangerConfirmText: dangerZoneState.dangerConfirmText || "",
      setDangerConfirmText: dangerZoneState.setDangerConfirmText,
      requestArchiveDoll: dangerZoneState.requestArchiveDoll,
      requestPermanentDelete: dangerZoneState.requestPermanentDelete,
      cancelDangerAction: dangerZoneState.cancelDangerAction,
      archiveDoll: dangerZoneState.archiveDoll,
      deleteDollPermanently: dangerZoneState.deleteDollPermanently,
    },
    digital: {
      selectedSlug: selectedSlug || "",
      copyToClipboard: browserActionsState.copyToClipboard,
      dataQualityHints: workspaceViewState.dataQualityHints || [],
      digitalHints: workspaceViewState.digitalHints || [],
      hasQrIdentity: Boolean(workspaceViewState.hasQrIdentity),
      qrIsSensitive: Boolean(workspaceViewState.qrIsSensitive),
      qrSensitivityLabel: workspaceViewState.qrSensitivityLabel || "",
      publicUrl: publicUrl || "",
      publicPath: publicPath || "",
      qrSensitivityText: workspaceViewState.qrSensitivityText || "",
      qrDataUrl: detailState.qrDataUrl || "",
      qrStatus: workspaceViewState.qrStatus || "",
      activateDigitalLayer: qrWorkflowState.activateDigitalLayer,
      savedQrUrl: workspaceViewState.savedQrUrl || "",
      generateQrCode: qrWorkflowState.generateQrCode,
      requestQrRegeneration: qrWorkflowState.requestQrRegeneration,
      qrUploading: Boolean(qrWorkflowState.qrUploading),
      qrReady: Boolean(workspaceViewState.qrReady),
      openPublicPage: browserActionsState.openPublicPage,
      downloadQrCode: qrWorkflowState.downloadQrCode,
      downloadPrintCard: qrWorkflowState.downloadPrintCard,
      qrReadinessMessage: workspaceViewState.qrReadinessMessage || "",
      showQrRegenerateWarning: Boolean(qrWorkflowState.showQrRegenerateWarning),
      setShowQrRegenerateWarning: qrWorkflowState.setShowQrRegenerateWarning,
      qrWarningMessage: workspaceViewState.qrWarningMessage || "",
      confirmQrRegeneration: qrWorkflowState.confirmQrRegeneration,
      printCardRef: qrWorkflowState.printCardRef,
      identity: detailState.identity,
    },
    operations: {
      filter: operationsFilter || "all",
      setFilter: setOperationsFilter,
      sort: operationsSort || "urgency",
      setSort: setOperationsSort,
      operationsSummaryItems: workspaceViewState.operationsSummaryItems || [],
      filteredOperationsByDoll: workspaceViewState.filteredOperationsByDoll || [],
      productionQueueGroups: workspaceViewState.productionQueueGroups || [],
      contentQueueGroups: workspaceViewState.contentQueueGroups || [],
      openDollWorkspace: selectionState.openDollWorkspace,
    },
    production: buildAdminProductionSectionState({
      selected,
      isProductionEditable: workspaceViewState.isProductionEditable,
      dollIdentityCollection: workspaceViewState.dollIdentityCollection,
      dollIdentityArtistDisplay: workspaceViewState.dollIdentityArtistDisplay,
      dollIdentityArtistIsEmpty: workspaceViewState.dollIdentityArtistIsEmpty,
      currentWorkflowStageLabel: workspaceViewState.currentWorkflowStageLabel,
      currentWorkflowStageStatus: workspaceViewState.currentWorkflowStageStatus,
      dollIdentityWorkflowState: workspaceViewState.dollIdentityWorkflowState,
      identity: detailState.identity,
      setIdentity: detailState.setIdentity,
      hasImage: workspaceViewState.hasImage,
      uploadImage: identityEditorState.uploadImage,
      saveIdentity: identityEditorState.saveIdentity,
    }),
    selection: buildAdminSelectionSectionState({
      selected,
      selectedIsArchived: workspaceViewState.selectedIsArchived,
      selectedReadinessOverall: workspaceViewState.selectedReadiness?.overall,
      currentSelectedWorkspaceMode: workspaceViewState.currentSelectedWorkspaceMode,
      setSelectedWorkspaceMode: selectionState.setSelectedWorkspaceMode,
      selectedWorkspaceHeading: workspaceViewState.selectedWorkspaceHeading,
      selectedWorkspaceSummary: workspaceViewState.selectedWorkspaceSummary,
      currentDepartment: workspaceViewState.currentDepartment,
      setActiveDepartment: selectionState.setActiveDepartment,
      currentStageView: workspaceViewState.currentStageView,
      setActiveStageView: selectionState.setActiveStageView,
    }),
    stageAction: buildAdminStageActionSectionState({
      warning: pipelineActionsState.stageActionWarning,
      clearWarning: clearStageActionWarning,
      confirmWarning: pipelineActionsState.confirmStageActionWarning,
    }),
    workspace: {
      workflowFeedback: workspaceViewState.workflowFeedback,
      productionWorkflowComplete: Boolean(workspaceViewState.productionWorkflowComplete),
      overviewBlockingItems: workspaceViewState.overviewBlockingItems || [],
      contentOverviewItems: workspaceViewState.contentOverviewItems || [],
      contentAssetCompleteness: workspaceViewState.contentAssetCompleteness || [],
      managedContentGenerating: Boolean(managedContentState.managedContentGenerating),
      contentPreviewHref: workspaceViewState.contentPreviewHref || "",
      selectedContentManagement: managedContentStoreState.selectedContentManagement,
      contentManagementNextStepGuidance:
        workspaceViewState.contentManagementNextStepGuidance || "",
      handleGenerateManagedContent: managedContentState.handleGenerateManagedContent,
      handlePreviewManagedContent: managedContentState.handlePreviewManagedContent,
      handleApproveManagedContent: managedContentState.handleApproveManagedContent,
      handlePublishManagedContent: managedContentState.handlePublishManagedContent,
      handleUnpublishManagedContent: managedContentState.handleUnpublishManagedContent,
      generatedContentEditState: managedContentState.generatedContentEditState,
      generatedContentSavingState: managedContentState.generatedContentSavingState,
      introScriptDraft: managedContentState.introScriptDraft || "",
      setIntroScriptDraft: managedContentState.setIntroScriptDraft,
      selectedGeneratedV1Content: managedContentStoreState.selectedGeneratedV1Content,
      startIntroScriptEditing: managedContentState.startIntroScriptEditing,
      cancelIntroScriptEditing: managedContentState.cancelIntroScriptEditing,
      saveIntroScriptEdit: managedContentState.saveIntroScriptEdit,
      storyPageDrafts: managedContentState.storyPageDrafts || [],
      setStoryPageDrafts: managedContentState.setStoryPageDrafts,
      startStoryPageEditing: managedContentState.startStoryPageEditing,
      cancelStoryPageEditing: managedContentState.cancelStoryPageEditing,
      saveStoryPageEdit: managedContentState.saveStoryPageEdit,
      playActivityDraft: managedContentState.playActivityDraft,
      setPlayActivityDraft: managedContentState.setPlayActivityDraft,
      startPlayActivityEditing: managedContentState.startPlayActivityEditing,
      cancelPlayActivityEditing: managedContentState.cancelPlayActivityEditing,
      savePlayActivityEdit: managedContentState.savePlayActivityEdit,
      selectedHasPlayActivityChoices: Boolean(
        workspaceViewState.selectedHasPlayActivityChoices
      ),
      selectedEditablePlayActivity: workspaceViewState.selectedEditablePlayActivity,
      dashboardSummaryItems: workspaceViewState.dashboardSummaryItems || [],
      dashboardNextStepMessage: workspaceViewState.dashboardNextStepMessage || "",
      dashboardRecommendedWorkspaceLabel:
        workspaceViewState.dashboardRecommendedWorkspaceLabel || "",
      dashboardRecommendedWorkspace: workspaceViewState.dashboardRecommendedWorkspace || "",
      selectedPipelineState: workspaceViewState.selectedPipelineState,
      currentOpenPipelineStage: workspaceViewState.currentOpenPipelineStage || "",
      pipelineStageActionBusy: Boolean(pipelineActionsState.pipelineStageActionBusy),
      pipelineStageCompleting: pipelineActionsState.pipelineStageCompleting || "",
      completePipelineStage: pipelineActionsState.completePipelineStage,
      requestReopenPipelineStage: pipelineActionsState.requestReopenPipelineStage,
      pipelineStageReopening: pipelineActionsState.pipelineStageReopening || "",
      showWorkflowGuidance: Boolean(workspaceViewState.showWorkflowGuidance),
      workflowGuidance: workspaceViewState.workflowGuidance || "",
      generateDraft: managedContentState.generateDraft,
    },
  };
}
